# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi

# setup environment for Rust lang
. "$HOME/.cargo/env"
export PATH

# Nano editor is default standart editor unfortunately
# so change it to Vim
export EDITOR=vim

# enter GPG passphrase from terminal
export SECRETS_PINENTRY=loopback
