#!/bin/bash

# git completion
source /usr/local/etc/profile.d/git-completion.bash

# brew completion
source /usr/local/etc/profile.d/brew_completion.bash

# bash completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

export JAVA_HOME="/Library/Internet_Plug-Ins/JavaAppletPlugin.plugin/Contents/Home"
export MAESTRO_CLI_HOME="/usr/local/opt/maestro-cli"
PATH="$PATH:$MAESTRO_CLI_HOME/bin"
PATH="$PATH:~/.local/bin:~/bin"

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
PATH="~/Library/Python/3.7/bin:${PATH}"
export PATH

#User's different staff
alias ls='ls -G'
#alias ll='ls -Glh'
#alias la='ls -GA'
#alias l='ls -GC'
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

#This is the default structure of the bash prompt on many Linux systems
#export PS1="\h@\u:\W\$ "
export PS1="[\[\e[1;31m\]\u@\h\[\e[m\]:\[\e[37m\]\w\[\e[m\]]\$ "

umask 0077


export PATH="$HOME/.cargo/bin:$PATH"
