# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# NOTE: commands from different sessions will be mixed in a history file
HISTFILESIZE=400000 # ensure a history file is big enough
HISTSIZE=10000 # limit the number of these lines to be retained in memory
# `PROMPT_COMMAND` - contains a command to be executed before any new prompt is shown
# `history -a` - an immediate write of all new history lines
PROMPT_COMMAND="${PROMPT_COMMAND:-:} ; history -a"
shopt -s histappend

# User specific aliases and functions
if [ -d ~/.bashrc.d ]; then
	for rc in ~/.bashrc.d/*; do
		if [ -f "$rc" ]; then
			. "$rc"
		fi
	done
fi

unset rc

# Compress a history file
# below script could be added to the `cron` for example or executed after each login
function del_duplicates() {
    awk 'NR==FNR && !/^#/{lines[$0]=FNR;next} lines[$0]==FNR' "$HISTFILE" "$HISTFILE" \
        > "$HISTFILE.compressed" && mv "$HISTFILE.compressed" "$HISTFILE"
}

alias lsofc='lsof -i |grep -Ei "(listen|established)"'

# Misc
umask 0077
